### PR TITLE
Remove invalid import

### PR DESCRIPTION
**Pull request by bkersbergen**

### CODE REVIEW

**Comment by n-s-f** [comment]
Thanks for the pull request, but I'm a little confused. The code in that module relies on this library: https://pypi.python.org/pypi/bezier.  What makes the import invalid?

Have you tried installing that library with `pip install bezier`?

**Comment by bkersbergen** [comment]
When removing that line the notebook runs fine on my pc.
Because bezier.py was importing bezier, i thought it was not suppose too do so.
Sorry for the confusion, i'll close this request.

**Comment by n-s-f** [comment]
Ah, I understand the confusion. Does everything work if you run `pip install bezier`?

**Comment by bkersbergen** [comment]
I found your github repo via google, I cloned it and run it directly.
The code in the notebook seems to work fine without the bezier dependency (except for that import statement). So I never realized it was a dependency.
I'm guessing that the example in the notebook doesnt use the bezier functions.

I just did the `pip install bezier` and everything stills works fine. Thanks and have a nice weekend, Barrie

**Pull request closed without merging**
